server:
  port: 8888
spring:
  application:
    name: ms-admin-config-server
#Configuracion Local
#  profiles:
#    active: native
#  cloud:
#    config:
#      server: 
#        native:
#          searchLocations: file:///D:/AmbDesarrollo/Cursos/2022/MS-02-2022-V2/ms-admin-server-data

#Configuracion Cloud (git)
  cloud:
    config:
      server:
        git:
          uri: https://github.com/christianCarranza/MSVC-VENTAS.git
          search-paths:
          - ms-admin-server-data
          username: carranzachristian61@gmail.com
          password: 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
          clone-on-start: true
          force-pull: true
          timeout: 5
          default-label: master